export const MENU_ITEMS = [
  {
    id: 'bobba',
    name: 'Bobba Special',
    category: 'juices',
    desc: 'Refreshing Lime · Pure Zesty Ginger · Sugarcane Blend',
    tag: "⭐ Today's Special • Best Seller",
    tagType: 'special',
    prices: { mid: 70, large: 100 },
    image: '/images/2fd (5).jpg',
    featured: true,
    available: true,
  },
  {
    id: 'suns-flower',
    name: "Sun's Flower",
    category: 'juices',
    desc: 'Tangy Passion Fruit · Sweet Organic Sugarcane',
    tag: 'Freshly Squeezed',
    prices: { mid: 80, large: 120 },
    image: '/images/2fd (7).jpg',
    featured: false,
    available: true,
  },
  {
    id: 'thick-mess',
    name: 'Thick Mess',
    category: 'juices',
    desc: 'Rich Mango Blend · Sweet Sugarcane',
    tag: 'Popular Favorite',
    prices: { mid: 80, large: 120 },
    image: '/images/2fd (1).jpg',
    featured: false,
    available: true,
  },
  {
    id: 'sweeet-cactus',
    name: 'Sweeet Cactus',
    category: 'juices',
    desc: 'Tropical Pineapple · Sweet Sugarcane Extract',
    tag: 'Freshly Squeezed',
    prices: { mid: 80, large: 120 },
    image: '/images/2fd (2).jpg',
    featured: false,
    available: true,
  },
  {
    id: 'tamarind',
    name: 'Pure Tamarind',
    category: 'juices',
    desc: 'Sweet & Tangy Cold Pressed Pure Tamarind',
    tag: 'Tangy Delight',
    prices: { mid: 80, large: 120 },
    image: '/images/2fd (4).jpg',
    featured: false,
    available: true,
  },
  {
    id: 'sweet-sensation',
    name: 'Sweet Sensation',
    category: 'juices',
    desc: 'Naturally Sweet Sugarcane · Fresh Zesty Lime',
    tag: 'Freshly Squeezed',
    prices: { mid: 70, large: 100 },
    image: '/images/2fd (6).jpg',
    featured: false,
    available: true,
  },
  {
    id: 'crimson-red',
    name: 'Crimson Red',
    category: 'juices',
    desc: 'Nutrient-Rich Beetroot · Sweet Sugarcane',
    tag: 'Power Antioxidant',
    prices: { mid: 70, large: 100 },
    image: '/images/2fd (3).jpg',
    featured: false,
    available: true,
  },
  {
    id: 'bana-splash',
    name: 'Bana Splash Smoothie',
    category: 'smoothies',
    desc: 'Creamy Fresh Banana · Tropical Fruit Blend',
    tag: 'Freshly Blended',
    prices: { mid: 80, large: 120 },
    image: '/images/2fd (1).jpg',
    featured: false,
    available: true,
  },
  {
    id: 'avocado',
    name: 'Avocado Cream',
    category: 'smoothies',
    desc: 'Smooth & Rich Creamy Hass Avocado Blend',
    tag: 'Creamy & Fresh',
    prices: { mid: 80, large: 120 },
    image: '/images/2fd (6).jpg',
    featured: false,
    available: true,
  },
  {
    id: 'sunkissed',
    name: 'Sunkissed Citrus',
    category: 'juices',
    desc: 'Zesty Citrus · Sun-Ripened Fresh Orange',
    tag: 'Citrus Burst',
    prices: { mid: 80, large: 120 },
    image: '/images/2fd (7).jpg',
    featured: false,
    available: true,
  },
  {
    id: 'minty-affair',
    name: 'Minty Affair',
    category: 'juices',
    desc: 'Refreshing Garden Mint · Zesty Lime Splash',
    tag: 'Cooling Herb',
    prices: { mid: 80, large: 120 },
    image: '/images/2fd (5).jpg',
    featured: false,
    available: true,
  },
  {
    id: 'bitter-herbs',
    name: 'Bitter Herbs Elixir',
    category: 'wellness',
    desc: 'Healing Pure Aloe Vera · Sugarcane · Zesty Ginger',
    tag: '🌿 Wellness Special',
    tagType: 'bitter',
    prices: { mid: 80, large: 120 },
    image: '/images/2fd (2).jpg',
    featured: true,
    available: true,
  },
  {
    id: 'simba-stick',
    name: 'Simba Stick Ice Cream',
    category: 'treats',
    desc: 'Flavours: Choc Delight, Choc Nut, White Choc & Nuts, Strawberry, Caramel Crunch',
    tag: '🍦 Cool Treat',
    prices: { single: 50 },
    image: '/images/7.jpg',
    featured: false,
    available: true,
  },
  {
    id: 'ice-pop',
    name: "Delight's Ice Pop",
    category: 'treats',
    desc: 'Lyons Maid Ice Pops — Orange, Cola, Lemon, Strawberry',
    tag: '❄️ Super Cool',
    prices: { single: 15 },
    image: '/images/8.jpg',
    featured: false,
    available: true,
  },
];

export const ADDONS = [
  { id: 'ginger', name: '🫚 Extra Ginger', price: 10 },
  { id: 'bobba', name: '🧋 Extra Bobba', price: 20 },
  { id: 'sugarcane', name: '🍯 Extra Sugarcane', price: 15 },
  { id: 'lime', name: '🍋 Extra Lime', price: 10 },
  { id: 'mint', name: '🌿 Extra Mint', price: 10 },
];

export const STORE_INFO = {
  name: 'PASH JUICES',
  tagline: '100% Raw Cold-Pressed Juices, Smoothies & Elixirs',
  mpesaTill: '4809304',
  phone: '+254798169278',
  whatsapp: '254798169278',
  address: 'Pash Juices Store, Kiambu / Nairobi',
  mapsUrl: 'https://www.google.com/maps/search/Delight%20Juice%20Bar/@-1.15264809,36.91776181,17z?hl=en',
};



